### ISSUE TITLE
RHEL package depend on CentOS specific version

### ISSUE THREAD

**Issue by KrisBuytaert** [phusion/passenger_rpm_automation#7]
When trying to install mod_passenger and passenger on a RHEL 7.2 box, they seem to require a CentOS specific version of selinux-policy

Red Hat Enterprise Linux Server release 7.2 (Maipo)
root@SL00285V:~ # rpm -qa | grep selinux
libselinux-utils-2.2.2-6.el7.x86_64
libselinux-python-2.2.2-6.el7.x86_64
docker-engine-selinux-1.9.1-1.el7.centos.noarch
libselinux-2.2.2-6.el7.x86_64
selinux-policy-targeted-3.13.1-60.el7.noarch
pe-ruby-selinux-2.0.94-4.pe.el7.x86_64
selinux-policy-3.13.1-60.el7.noarch
root@SL00285V:~ # yum localinstall mod_passenger-5.0.26-8.el7.x86_64.rpm passenger-5.0.26-8.el7.x86_64.rpm 
Loaded plugins: versionlock
Examining mod_passenger-5.0.26-8.el7.x86_64.rpm: mod_passenger-5.0.26-8.el7.x86_64
Marking mod_passenger-5.0.26-8.el7.x86_64.rpm to be installed
Examining passenger-5.0.26-8.el7.x86_64.rpm: passenger-5.0.26-8.el7.x86_64
Marking passenger-5.0.26-8.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mod_passenger.x86_64 0:5.0.26-8.el7 will be installed
--> Processing Dependency: httpd-mmn = 20120211x8664 for package: mod_passenger-5.0.26-8.el7.x86_64
vdabwarez                                                                                       | 1.1 kB  00:00:00  
--> Processing Dependency: libapr-1.so.0()(64bit) for package: mod_passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: libaprutil-1.so.0()(64bit) for package: mod_passenger-5.0.26-8.el7.x86_64
---> Package passenger.x86_64 0:5.0.26-8.el7 will be installed
--> Processing Dependency: selinux-policy >= 3.13.1-60.el7_2.3 for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: /usr/bin/ruby for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: ruby(release) for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: rubygem(rack) for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: rubygem(rake) for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: rubygems for package: passenger-5.0.26-8.el7.x86_64
--> Processing Dependency: libruby.so.2.0()(64bit) for package: passenger-5.0.26-8.el7.x86_64
--> Running transaction check
---> Package apr.x86_64 0:1.4.8-3.el7 will be installed
---> Package apr-util.x86_64 0:1.5.2-6.el7 will be installed
---> Package httpd.x86_64 0:2.4.6-40.el7 will be installed
--> Processing Dependency: httpd-tools = 2.4.6-40.el7 for package: httpd-2.4.6-40.el7.x86_64
--> Processing Dependency: /etc/mime.types for package: httpd-2.4.6-40.el7.x86_64
---> Package passenger.x86_64 0:5.0.26-8.el7 will be installed
--> Processing Dependency: selinux-policy >= 3.13.1-60.el7_2.3 for package: passenger-5.0.26-8.el7.x86_64
---> Package ruby.x86_64 0:2.0.0.598-25.el7_1 will be installed
--> Processing Dependency: rubygem(bigdecimal) >= 1.2.0 for package: ruby-2.0.0.598-25.el7_1.x86_64
---> Package ruby-libs.x86_64 0:2.0.0.598-25.el7_1 will be installed
---> Package rubygem-rack.noarch 1:1.5.2-4.el7 will be installed
---> Package rubygem-rake.noarch 0:0.9.6-25.el7_1 will be installed
---> Package rubygems.noarch 0:2.0.14-25.el7_1 will be installed
--> Processing Dependency: rubygem(rdoc) >= 4.0.0 for package: rubygems-2.0.14-25.el7_1.noarch
--> Processing Dependency: rubygem(psych) >= 2.0.0 for package: rubygems-2.0.14-25.el7_1.noarch
--> Processing Dependency: rubygem(io-console) >= 0.4.2 for package: rubygems-2.0.14-25.el7_1.noarch
--> Running transaction check
---> Package httpd-tools.x86_64 0:2.4.6-40.el7 will be installed
---> Package mailcap.noarch 0:2.1.41-2.el7 will be installed
---> Package passenger.x86_64 0:5.0.26-8.el7 will be installed
--> Processing Dependency: selinux-policy >= 3.13.1-60.el7_2.3 for package: passenger-5.0.26-8.el7.x86_64
---> Package rubygem-bigdecimal.x86_64 0:1.2.0-25.el7_1 will be installed
---> Package rubygem-io-console.x86_64 0:0.4.2-25.el7_1 will be installed
---> Package rubygem-psych.x86_64 0:2.0.0-25.el7_1 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: rubygem-psych-2.0.0-25.el7_1.x86_64
---> Package rubygem-rdoc.noarch 0:4.0.0-25.el7_1 will be installed
--> Processing Dependency: ruby(irb) = 2.0.0.598 for package: rubygem-rdoc-4.0.0-25.el7_1.noarch
--> Processing Dependency: rubygem(json) >= 1.7.7 for package: rubygem-rdoc-4.0.0-25.el7_1.noarch
--> Running transaction check
---> Package libyaml.x86_64 0:0.1.4-11.el7_0 will be installed
---> Package passenger.x86_64 0:5.0.26-8.el7 will be installed
--> Processing Dependency: selinux-policy >= 3.13.1-60.el7_2.3 for package: passenger-5.0.26-8.el7.x86_64
---> Package ruby-irb.noarch 0:2.0.0.598-25.el7_1 will be installed
---> Package rubygem-json.x86_64 0:1.8.3-1 will be installed
--> Finished Dependency Resolution
Error: Package: passenger-5.0.26-8.el7.x86_64 (/passenger-5.0.26-8.el7.x86_64)
           Requires: selinux-policy >= 3.13.1-60.el7_2.3
           Installed: selinux-policy-3.13.1-60.el7.noarch (@anaconda/7.2)
               selinux-policy = 3.13.1-60.el7
           Available: selinux-policy-3.12.1-153.el7.noarch (rhel-7-server-rpms)
               selinux-policy = 3.12.1-153.el7
           Available: selinux-policy-3.12.1-153.el7_0.10.noarch (rhel-7-server-rpms)
               selinux-policy = 3.12.1-153.el7_0.10
           Available: selinux-policy-3.12.1-153.el7_0.11.noarch (rhel-7-server-rpms)
               selinux-policy = 3.12.1-153.el7_0.11
           Available: selinux-policy-3.12.1-153.el7_0.12.noarch (rhel-7-server-rpms)
               selinux-policy = 3.12.1-153.el7_0.12
           Available: selinux-policy-3.12.1-153.el7_0.13.noarch (rhel-7-server-rpms)
               selinux-policy = 3.12.1-153.el7_0.13
           Available: selinux-policy-3.13.1-23.el7.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7
           Available: selinux-policy-3.13.1-23.el7_1.7.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.7
           Available: selinux-policy-3.13.1-23.el7_1.8.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.8
           Available: selinux-policy-3.13.1-23.el7_1.13.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.13
           Available: selinux-policy-3.13.1-23.el7_1.17.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.17
           Available: selinux-policy-3.13.1-23.el7_1.18.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.18
           Available: selinux-policy-3.13.1-23.el7_1.21.noarch (rhel-7-server-rpms)
               selinux-policy = 3.13.1-23.el7_1.21
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

On CentOS 7.2 

[root@centos-7 ~]# rpm -qa | grep selinux-policy
selinux-policy-3.13.1-60.el7_2.3.noarch
selinux-policy-targeted-3.13.1-60.el7_2.3.noarch

These packages do exist.

**Comment by hughesjr** [comment]
That file should be in RHEL 7 .. here is the announcement:

https://rhn.redhat.com/errata/RHBA-2016-0191.html
